window:
  title: Kort
  size: [920, 640]
  fps: 60

game:
  players:
    - type: human
      name: Arthur
    - type: robot
      name: Elioenai
      file: "saved_models/Session 2020-10-31 151358/9600 iterations (2020-10-31 175300)/models/Elioenai.bot"
